language: node_js
node_js:
- 10.16.0
cache:
  directories:
  - node_modules
install:
- npm install
before_script: 
script:
- npm run build-cdn
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 139.199.14.123
before_install:
- openssl aes-256-cbc -K $encrypted_4085335f39b4_key -iv $encrypted_4085335f39b4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa   #还是Linux文件权限问题
- cd dist
- scp -r *.html travis@139.199.14.123:/usr/share/nginx/orion
